### ISSUE TITLE
cmake configuration fails

### ISSUE THREAD

**Issue by mchalupa** [grievejia/andersen#1]
Hi,

when I run cmake, I get this error due to missing CMakeLists.txt (googletest is added as subdirectory to cmake)

```
CMake Error at unittest/CMakeLists.txt:1 (add_subdirectory):
  The source directory

    /home/marek/statica/andersen/unittest/googletest

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!
```

**Comment by grievejia** [comment]
I did another commit to fix the googletest issue. Please pull again and see if it works.

**Comment by mchalupa** [comment]
Yes, now cmake works smoothly, thanks
