### ISSUE TITLE
Possible bug when constructing constraint graph ?

### ISSUE THREAD

**Issue by yiyuaner** [grievejia/andersen#4]
In ConstraintSolving.cpp:
```
void buildConstraintGraph(ConstraintGraph &cGraph,
                          const std::vector<AndersConstraint> &constraints,
                          AndersNodeFactory &nodeFactory,
                          std::map<NodeIndex, AndersPtsSet> &ptsGraph) {
  for (auto const &c : constraints) {
    NodeIndex srcTgt = nodeFactory.getMergeTarget(c.getSrc());
    NodeIndex dstTgt = nodeFactory.getMergeTarget(c.getDest());
    switch (c.getType()) {
    ......
    case AndersConstraint::STORE: {
      cGraph.insertStoreEdge(dstTgt, srcTgt);
      break;
    }
    ......
    }
  }
}
```
When there's an AndersConstraint::STORE representing "*dst = src", we need an edge from src to dst, 
right? I think the correct code should be:
```
cGraph.insertStoreEdge(srcTgt, dstTgt);
```

**Comment by grievejia** [comment]
Thanks for the report!
Unfortunately, I haven't touched the code for years and almost forgot how it works. So I can't really recall immediately at this point why the edge is from `dstTgt` to `srcTgt` :(
One thing I know for sure is that the analysis was heavily tested before I released it. As a result, I think the chance of having the edge pointed in the wrong direction is going to be slim. That being said, I'll look into this when I have more leisure time.

**Comment by yiyuaner** [comment]
I think the code is correct. It corresponds to the following code fragment in the same file:
```
for (auto const &dst : cNode->stores()) {
    NodeIndex tgtNode = nodeFactory.getMergeTarget(dst);
    if (constraintGraph.insertCopyEdge(tgtNode, vRep)) {
        // errs() << "\tInsert copy edge " << tgtNode << " -> " << v <<
        // "\n";
        nextWorkList->enqueue(tgtNode);
   }
```
